/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.pss.criacaomanutencaousuarios.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author André
 */
public class RebaixarUsuarioView extends javax.swing.JInternalFrame {

    /**
     * Creates new form RebaixarUsuarioView
     */
    public RebaixarUsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRebaixar = new javax.swing.JButton();
        lblPromoverUsuarios = new javax.swing.JLabel();
        txtUsuarios = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtNomeUsuario = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("Insira o nome do Usuario que deseja rebaixar:");

        btnRebaixar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRebaixar.setText("Rebaixar");
        btnRebaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRebaixarActionPerformed(evt);
            }
        });

        lblPromoverUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPromoverUsuarios.setText("Rebaixar Usuarios");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtUsuarios.setViewportView(jTextArea1);

        txtNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPromoverUsuarios)
                    .addComponent(btnRebaixar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarios)
                    .addComponent(txtNomeUsuario))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblPromoverUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRebaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRebaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRebaixarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRebaixarActionPerformed

    private void txtNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRebaixar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblPromoverUsuarios;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JScrollPane txtUsuarios;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnRebaixar() {
        return btnRebaixar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public JLabel getLblPromoverUsuarios() {
        return lblPromoverUsuarios;
    }

    public JTextField getTxtNomeUsuario() {
        return txtNomeUsuario;
    }

    public JScrollPane getTxtUsuarios() {
        return txtUsuarios;
    }

}
