/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pss.criacaomanutencaousuarios.view;

import javax.swing.JMenuItem;

/**
 * @author André Tavares Louzada, Lucas Herbest Lopes e Yuri Sousa Almeida
 */
public class SistemaView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SistemaView.class.getName());

    /**
     * Creates new form SistemaView
     */
    public SistemaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnbSistema = new javax.swing.JMenuBar();
        mnuUsuario = new javax.swing.JMenu();
        mnuNotificacoes = new javax.swing.JMenu();
        mitVisualizarNotificacoes = new javax.swing.JMenuItem();
        mitEnviarNotificacoes = new javax.swing.JMenuItem();
        mnuSistema = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuUsuario.setText("Usuário");
        mnbSistema.add(mnuUsuario);

        mnuNotificacoes.setText("Notificações");

        mitVisualizarNotificacoes.setText("Visualizar notificações");
        mnuNotificacoes.add(mitVisualizarNotificacoes);

        mitEnviarNotificacoes.setText("Enviar notificações");
        mnuNotificacoes.add(mitEnviarNotificacoes);

        mnbSistema.add(mnuNotificacoes);

        mnuSistema.setText("Sistema");
        mnbSistema.add(mnuSistema);

        setJMenuBar(mnbSistema);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mitEnviarNotificacoes;
    private javax.swing.JMenuItem mitVisualizarNotificacoes;
    private javax.swing.JMenuBar mnbSistema;
    private javax.swing.JMenu mnuNotificacoes;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenu mnuUsuario;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMitEnviarNotificacoes() {
        return mitEnviarNotificacoes;
    }

    public JMenuItem getMitVisualizarNotificacoes() {
        return mitVisualizarNotificacoes;
    }
}
